module.exports = {
  content: ["./components/marketing/**/*.{ts,tsx}"],
  css: ["./public/assets/css/main.css"],
  output: "./public/assets/css/purged",

  safelist: [
    "active",
    "show",
    "open",
    "collapsed",
    "collapsing",
    "disabled",
    /^btn/,
    /^navbar/,
    /^nav/,
    /^dropdown/,
    /^modal/,
    /^offcanvas/,
    /^collapse/,
    /^container/,
    /^row$/,
    /^col/,
    /^d-/,
    /^p-/,
    /^m-/,
    /^text-/,
    /^bg-/,
  ],
};
